version: '3.6'
services:
  uecluster-admin:
    image: 'SET_CURRENT_IMAGE'
    environment:
      - MODE=SET_MODE
      - UECLUSTER_DB_HOST="SET_UECLUSTER_DB_HOST"
      - UECLUSTER_DB_PORT=SET_UECLUSTER_DB_PORT
      - UECLUSTER_DB_NAME="SET_UECLUSTER_DB_NAME"
      - UECLUSTER_DB_USER="SET_UECLUSTER_DB_USER"
      - UECLUSTER_DB_PASSWORD="SET_UECLUSTER_DB_PASSWORD"
      - UECLUSTER_AZURE_ACCOUNT_NAME="SET_UECLUSTER_AZURE_ACCOUNT_NAME"
      - UECLUSTER_AZURE_ACCOUNT_KEY="SET_UECLUSTER_AZURE_ACCOUNT_KEY"
    deploy:
     replicas: SET_REPLICAS
    ports:
        - "SET_PORT:80"
